/**
 * YoCore canonical error codes.
 *
 * Source of truth — every API response with a 4xx/5xx status returns one of these
 * as `error` in the response body. See /docs/error-codes.md for full table + meanings.
 *
 * Rules:
 *   - APPEND-ONLY in practice; renames/removals require deprecation + version bump.
 *   - Keep grouped + alphabetical within a group.
 *   - Every code MUST have an entry in http-status-map.ts (CI enforced).
 */
export const ErrorCode = {
  // ─── Authentication ──────────────────────────────────────────────
  AUTH_ACCOUNT_BANNED: 'AUTH_ACCOUNT_BANNED',
  AUTH_ACCOUNT_DELETED: 'AUTH_ACCOUNT_DELETED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_BOOTSTRAP_ALREADY_DONE: 'AUTH_BOOTSTRAP_ALREADY_DONE',
  AUTH_BOOTSTRAP_SECRET_INVALID: 'AUTH_BOOTSTRAP_SECRET_INVALID',
  AUTH_EMAIL_INVALID: 'AUTH_EMAIL_INVALID',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_HOSTED_REDIRECT_NOT_ALLOWED: 'AUTH_HOSTED_REDIRECT_NOT_ALLOWED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_MFA_INVALID_CODE: 'AUTH_MFA_INVALID_CODE',
  AUTH_MFA_NOT_ENROLLED: 'AUTH_MFA_NOT_ENROLLED',
  AUTH_MFA_RECOVERY_NO_CODES: 'AUTH_MFA_RECOVERY_NO_CODES',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_PASSWORD_POLICY_VIOLATION: 'AUTH_PASSWORD_POLICY_VIOLATION',
  AUTH_PKCE_VERIFIER_MISMATCH: 'AUTH_PKCE_VERIFIER_MISMATCH',
  AUTH_REFRESH_REUSED: 'AUTH_REFRESH_REUSED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_ONBOARDING_ALREADY_COMPLETE: 'AUTH_ONBOARDING_ALREADY_COMPLETE',

  // ─── API Key / Product Auth ──────────────────────────────────────
  APIKEY_INVALID: 'APIKEY_INVALID',
  APIKEY_MISSING: 'APIKEY_MISSING',
  APIKEY_PRODUCT_INACTIVE: 'APIKEY_PRODUCT_INACTIVE',
  CORS_ORIGIN_NOT_ALLOWED: 'CORS_ORIGIN_NOT_ALLOWED',
  IP_NOT_ALLOWLISTED: 'IP_NOT_ALLOWLISTED',

  // ─── Validation / Request ────────────────────────────────────────
  BODY_TOO_LARGE: 'BODY_TOO_LARGE',
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  IDEMPOTENCY_KEY_IN_PROGRESS: 'IDEMPOTENCY_KEY_IN_PROGRESS',
  IDEMPOTENCY_KEY_MISSING: 'IDEMPOTENCY_KEY_MISSING',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // ─── Resource ────────────────────────────────────────────────────
  BUNDLE_NOT_FOUND: 'BUNDLE_NOT_FOUND',
  GATEWAY_NOT_FOUND: 'GATEWAY_NOT_FOUND',
  INVITATION_ALREADY_USED: 'INVITATION_ALREADY_USED',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',

  // ─── Permission ──────────────────────────────────────────────────
  OWNER_ONLY: 'OWNER_ONLY',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SUPER_ADMIN_ONLY: 'SUPER_ADMIN_ONLY',
  WRONG_PRODUCT_SCOPE: 'WRONG_PRODUCT_SCOPE',

  // ─── Quota ───────────────────────────────────────────────────────
  EXPORT_COOLDOWN: 'EXPORT_COOLDOWN',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  SEAT_LIMIT_EXCEEDED: 'SEAT_LIMIT_EXCEEDED',
  WORKSPACE_LIMIT_EXCEEDED: 'WORKSPACE_LIMIT_EXCEEDED',

  // ─── Billing / Gateway ───────────────────────────────────────────
  BILLING_BUNDLE_ELIGIBILITY_BLOCKED: 'BILLING_BUNDLE_ELIGIBILITY_BLOCKED',
  BILLING_BUNDLE_VALIDATION_FAILED: 'BILLING_BUNDLE_VALIDATION_FAILED',
  BILLING_COUPON_EXHAUSTED: 'BILLING_COUPON_EXHAUSTED',
  BILLING_COUPON_INVALID: 'BILLING_COUPON_INVALID',
  BILLING_DOWNGRADE_BLOCKED: 'BILLING_DOWNGRADE_BLOCKED',
  BILLING_GATEWAY_CIRCUIT_OPEN: 'BILLING_GATEWAY_CIRCUIT_OPEN',
  BILLING_GATEWAY_CONFIG_MISSING: 'BILLING_GATEWAY_CONFIG_MISSING',
  BILLING_GATEWAY_UNAVAILABLE: 'BILLING_GATEWAY_UNAVAILABLE',
  BILLING_NO_PAYMENT_METHOD: 'BILLING_NO_PAYMENT_METHOD',
  BILLING_PAYMENT_FAILED: 'BILLING_PAYMENT_FAILED',
  BILLING_PLAN_IMMUTABLE: 'BILLING_PLAN_IMMUTABLE',
  BILLING_PLAN_MEMBER_OVERFLOW: 'BILLING_PLAN_MEMBER_OVERFLOW',
  BILLING_PLAN_NOT_PUBLISHED: 'BILLING_PLAN_NOT_PUBLISHED',
  BILLING_SUBSCRIPTION_NOT_ACTIVE: 'BILLING_SUBSCRIPTION_NOT_ACTIVE',
  BILLING_TRIAL_INELIGIBLE: 'BILLING_TRIAL_INELIGIBLE',
  BILLING_USAGE_HARD_CAP_EXCEEDED: 'BILLING_USAGE_HARD_CAP_EXCEEDED',
  GATEWAY_CREDENTIALS_INVALID: 'GATEWAY_CREDENTIALS_INVALID',
  GATEWAY_VERIFICATION_FAILED: 'GATEWAY_VERIFICATION_FAILED',

  // ─── Webhooks ────────────────────────────────────────────────────
  WEBHOOK_EVENT_DUPLICATE: 'WEBHOOK_EVENT_DUPLICATE',
  WEBHOOK_PAYLOAD_INVALID: 'WEBHOOK_PAYLOAD_INVALID',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_TIMESTAMP_OUT_OF_TOLERANCE: 'WEBHOOK_TIMESTAMP_OUT_OF_TOLERANCE',

  // ─── Rate Limiting ───────────────────────────────────────────────
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // ─── Server / external ───────────────────────────────────────────
  CACHE_UNAVAILABLE: 'CACHE_UNAVAILABLE',
  DB_UNAVAILABLE: 'DB_UNAVAILABLE',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  S3_UNAVAILABLE: 'S3_UNAVAILABLE',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // ─── GDPR / Compliance ───────────────────────────────────────────
  GDPR_DELETION_BLOCKED: 'GDPR_DELETION_BLOCKED',
  GDPR_DELETION_PENDING: 'GDPR_DELETION_PENDING',
  TOS_NOT_ACCEPTED: 'TOS_NOT_ACCEPTED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
